### ISSUE TITLE
Thank you 

### ISSUE THREAD

**Issue by ekg** [MitI-7/WaveletMatrix#1]
The world was missing a dynamic wavelet matrix implementation. Despite several publications in the topic, no code ever materialized. Thanks!

Have you described this code in a publication? What are you using it for?

**Comment by MitI-7** [comment]
@ekg 

Sorry. There is no description of this code.

I use this for competitive programming. For example, this problem can be solved using dynamic wavelet matrix.
(http://judge.u-aizu.ac.jp/onlinejudge/description.jsp?id=DSL_2_A&lang=en)
(http://judge.u-aizu.ac.jp/onlinejudge/review.jsp?rid=4528617#1)

**Comment by ekg** [comment]
Would you be interested in being part of a paper on a related library? I have started porting this code into that repo. The major change is to use a configurable succinct rank/select bitvector from it. I'll post code when I've debugged it.

**Comment by ekg** [comment]
https://github.com/xxsds/DYNAMIC is the library I'm referring to

**Comment by ekg** [comment]
My initial tests show a large performance improvement for rank and select when using DYNAMIC's succinct bitvector class. This comes at almost no loss of performance for dynamic operations:

```
-> % ./test-wm | head -7
SPEED
access:1405ms
rank:1695ms
select:2343ms
insert:1440ms
erase:2529ms
update:4767ms
```

Using DYNAMIC's bitvector:

```
SPEED         
access:271ms  
rank:343ms    
select:1234ms 
insert:1559ms 
erase:2010ms  
update:4219ms 
```

This could be useful for you. I'll mention you in the PR there so you can inspect it.

**Comment by MitI-7** [comment]
Thank you! I'll take a look at that library.

**Comment by MitI-7** [comment]
ekg's pull requests have been merged.
https://github.com/xxsds/DYNAMIC/pull/21
